[[databaselist]]
name = "test"
desc = "This is a sqlite test db"
driver = 'sqlite'
source = 'file:./data/test.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)&_pragma=synchronous(NORMAL)'
maxidleconn = 1
maxopenconn = 3
connmaxlifetime = '1h'

[[databaselist]]
name = "test"
desc = "This is a mysql test db"
driver = 'mysql'
source = 'localhost:3306'
maxidleconn = 3
maxopenconn = 5
connmaxlifetime = '1h'

[[redislist]]
name = "test"
desc = "This is a redis test db"
addr = '127.0.0.1:6379'
db = 1
dialtimeout = 3
readtimeout = 1
writetimeout = 1
